import datetime
from typing import List, Dict, Any


class BaseSchemaConfig:
    # The schema is generated by default using aliases as keys.
    # We want the snake_case name output.
    # Modified from:
    # - https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization
    @staticmethod
    def schema_extra(schema: Dict[str, Any], model) -> None:
        snake_case = {}

        for field in model.__fields__.values():
            k = field.name
            v = schema['properties'][field.alias]
            snake_case.update({k: v})

        schema.update({'properties': snake_case})


def get_current_datetime() -> datetime.datetime:
    return datetime.datetime.utcnow()
