# Generated by Django 3.0.6 on 2020-05-28 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rental_date', models.DateTimeField(default=datetime.datetime.today, editable=False)),
                ('return_date', models.DateTimeField(default=None, editable=False)),
                ('fee', models.FloatField(default=0, editable=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_store.Movie')),
            ],
        ),
    ]
