# Generated by Django 3.0.6 on 2020-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0003_auto_20200528_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
