# Generated by Django 3.0.6 on 2020-05-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0005_auto_20200528_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
