# Generated by Django 3.0.6 on 2020-05-28 17:39

from django.db import migrations, models
import movie_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0006_auto_20200528_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(default=movie_store.models.get_current_datetime, editable=False),
        ),
    ]
