# Generated by Django 3.0.6 on 2020-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_store', '0007_auto_20200528_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
